### ISSUE TITLE
Cannot read property 'createPage' of undefined

### ISSUE THREAD

**Issue by lukesnowden** [ajam/banquo-server#4]
Im guessing this is either a permissions or some sort of software related restriction as I can run this on my mac, but when trying to run on DigitalOcean i get the following in the log file: 

```
Express server listening on port 3000
Requesting http://america.aljazeera.com
/root/banquo-server/node_modules/banquo/src/banquo.js:36
    ph.createPage(openPage);
      ^
TypeError: Cannot read property 'createPage' of undefined
    at createPage (/root/banquo-server/node_modules/banquo/src/banquo.js:36:7)
    at /root/banquo-server/node_modules/node-phantom/node-phantom.js:65:6
    at null._onTimeout (/root/banquo-server/node_modules/node-phantom/node-phantom.js:43:5)
    at Timer.listOnTimeout (timers.js:110:15)
error: Forever detected script exited with code: 1
error: Script restart attempt #7
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
```

any idea what the problem is?

regards

**Comment by lukesnowden** [comment]
my fault, phantom not installed

**Comment by mhkeller** [comment]
No worries. Let me know if you run into any issues. The current banquo-server set up doesn't use the latest version of banquo but it should still work. There's a bug in the latest version of the node Phantom driver for v2.0 so install 1.9.8 per https://github.com/kevinschaul/depict/issues/15
